// Code generated by goagen v1.1.0-dirty, command line:
// $ goagen
// --design=github.com/upamune/goa-playground/design
// --out=$(GOPATH)/src/github.com/upamune/goa-playground
// --version=v1.1.0-dirty
//
// API "adder": Application User Types
//
// The content of this file is auto-generated, DO NOT MODIFY

package app
